version: "3.9"

volumes:
  pg-data:

services:
  postgres:
    image: postgres:12.7-alpine
    environment:
      POSTGRES_DB: "monitoring_system"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"